---
# tasks file for jenkins_server_role

- name: Run apt-get update
  ansible.builtin.apt:
    update_cache: yes
  changed_when: false # Don't report 'changed' for a simple update

- name: Install prerequisite packages
  ansible.builtin.apt:
    name:
      - openjdk-17-jre
      - ca-certificates
      - curl
      - git
    state: present

# --- Install Docker ---
- name: Ensure /etc/apt/keyrings directory exists
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download Docker's official GPG key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'
    force: true

- name: Add Docker's repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    filename: docker

- name: Install Docker Engine
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
    update_cache: yes

- name: Start and enable Docker service
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes

# --- Install Jenkins ---
- name: Ensure /usr/share/keyrings directory exists
  ansible.builtin.file:
    path: /usr/share/keyrings
    state: directory
    mode: '0755'

- name: Download Jenkins's GPG key
  ansible.builtin.get_url:
    url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
    dest: /usr/share/keyrings/jenkins-keyring.asc
    mode: '0644'
    force: true

- name: Add Jenkins's repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/"
    state: present
    filename: jenkins

- name: Install Jenkins
  ansible.builtin.apt:
    name: jenkins
    state: present
    update_cache: yes

- name: Start and enable Jenkins service
  ansible.builtin.service:
    name: jenkins
    state: started
    enabled: yes

- name: Wait for Jenkins to start up
  ansible.builtin.wait_for:
    port: 8080
    delay: 15
    timeout: 60

# --- Add Jenkins to Docker group ---
- name: Add 'jenkins' user to the 'docker' group
  ansible.builtin.user:
    name: jenkins
    groups: docker
    append: yes
  notify: Reboot server

# --- Install kubectl ---
- name: Download Kubernetes's GPG key
  ansible.builtin.get_url:
    url: https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key
    dest: /etc/apt/keyrings/kubernetes-apt-keyring.asc
    mode: '0644'
    force: true

- name: Add Kubernetes's repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.asc] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /"
    state: present
    filename: kubernetes

- name: Install kubectl
  ansible.builtin.apt:
    name: kubectl
    state: present
    update_cache: yes
